const crypto=require('crypto');const{db}=require('../../config/database.config');
async function usersByCategory(ids=[],connection=db){if(!ids.length)return{};const p=ids.map(()=>'?').join(',');const[rows]=await connection.query(`SELECT id,category_id,central_user_id,is_primary,is_active,created_at,updated_at FROM master_category_users WHERE category_id IN (${p}) ORDER BY category_id,is_primary DESC,created_at`,ids);return rows.reduce((o,r)=>{(o[r.category_id]??=[]).push(r);return o;},{});}
async function findAll({search,central_user_id,main_category,sub_category,brand_category,is_active}={}){const params=[];let sql=`SELECT id,detail_category,sub_category,main_category,brand_category,is_active,created_at,updated_at FROM master_categories WHERE 1=1`;if(search){sql+=` AND (detail_category LIKE ? OR sub_category LIKE ? OR main_category LIKE ? OR brand_category LIKE ?)`;params.push(...Array(4).fill(`%${search}%`));}if(central_user_id){sql+=` AND EXISTS (SELECT 1 FROM master_category_users mcu WHERE mcu.category_id=master_categories.id AND mcu.central_user_id=?)`;params.push(central_user_id);}for(const[k,c]of[['main_category','main_category'],['sub_category','sub_category'],['brand_category','brand_category']])if(arguments[0]?.[k]){sql+=` AND ${c}=?`;params.push(arguments[0][k]);}if(is_active!==undefined&&is_active!==''){sql+=` AND is_active=?`;params.push(Number(is_active));}sql+=` ORDER BY detail_category`;const[rows]=await db.query(sql,params);const users=await usersByCategory(rows.map(r=>r.id));return rows.map(r=>({...r,users:users[r.id]||[]}));}
async function findById(id,connection=db){const[rows]=await connection.query(`SELECT id,detail_category,sub_category,main_category,brand_category,is_active,created_at,updated_at FROM master_categories WHERE id=? LIMIT 1`,[id]);if(!rows[0])return null;const u=await usersByCategory([id],connection);return{...rows[0],users:u[id]||[]};}
async function create(data,connection=db){const id=crypto.randomUUID();await connection.query(`INSERT INTO master_categories (id,detail_category,sub_category,main_category,brand_category,is_active) VALUES (?,?,?,?,?,?)`,[id,data.detail_category,data.sub_category,data.main_category,data.brand_category,data.is_active]);return id;}
async function update(id,data,connection=db){return(await connection.query(`UPDATE master_categories SET detail_category=?,sub_category=?,main_category=?,brand_category=?,is_active=?,updated_at=NOW() WHERE id=?`,[data.detail_category,data.sub_category,data.main_category,data.brand_category,data.is_active,id]))[0];}
async function replaceUsers(categoryId,users=[],connection=db){await connection.query(`DELETE FROM master_category_users WHERE category_id=?`,[categoryId]);if(!users.length)return[];const values=users.map((u,i)=>[crypto.randomUUID(),categoryId,u.central_user_id,u.is_primary??(i===0?1:0),u.is_active??1]);await connection.query(`INSERT INTO master_category_users (id,category_id,central_user_id,is_primary,is_active) VALUES ?`,[values]);return(await usersByCategory([categoryId],connection))[categoryId]||[];}
async function remove(id){return(await db.query(`DELETE FROM master_categories WHERE id=?`,[id]))[0];}async function countUsedByItemParents(id){const[r]=await db.query(`SELECT COUNT(*) total FROM item_parents WHERE category_id=?`,[id]);return r[0]?.total||0;}async function updateStatus(id,v){return(await db.query(`UPDATE master_categories SET is_active=?,updated_at=NOW() WHERE id=?`,[v,id]))[0];}
async function transaction(cb){const c=await db.getConnection();try{await c.beginTransaction();const r=await cb(c);await c.commit();return r;}catch(e){await c.rollback();throw e;}finally{c.release();}}
module.exports={findAll,findById,create,update,replaceUsers,remove,countUsedByItemParents,updateStatus,transaction};
