const BrandModel = require('../../models/master/brand.model');
const ActivityLogService = require('../activity-log.service');
const DirectoryService = require('../pilargroup-directory.service');

function makeError(message,statusCode=400,code='ERROR',errors=null){const e=new Error(message);e.statusCode=statusCode;e.code=code;e.errors=errors;return e;}
function isValidBoolean(v){return [0,1,'0','1',true,false].includes(v);}
function normalizeBoolean(v,d=0){return v===undefined||v===null||v===''?d:(Number(v)?1:0);}
function normalizePayload(payload){return {code:String(payload.code||'').trim(),name:String(payload.name||'').trim(),is_active:payload.is_active??1,channels:payload.channels??[]};}
function validatePayload(payload){const errors={};if(!payload.code)errors.code='Code is required';if(!payload.name)errors.name='Name is required';if(payload.code.length>50)errors.code='Code cannot be longer than 50 characters';if(payload.name.length>100)errors.name='Name cannot be longer than 100 characters';if(!isValidBoolean(payload.is_active))errors.is_active='Is active must be 0 or 1';if(!Array.isArray(payload.channels))errors.channels='Channels must be an array';if(Object.keys(errors).length)throw makeError('Validation failed',422,'VALIDATION_ERROR',errors);}
function normalizeChannels(channels=[]){const seen=new Set();let primaryCount=0;const out=channels.map((c,index)=>{if(!c||!c.business_unit_id||!c.department_id)throw makeError(`Channel at index ${index} is invalid`,422,'VALIDATION_ERROR');const key=`${c.business_unit_id}:${Number(c.department_id)}`;if(seen.has(key))throw makeError('Duplicate channel in request',422,'VALIDATION_ERROR');seen.add(key);const row={business_unit_id:String(c.business_unit_id),department_id:Number(c.department_id),channel_name:c.channel_name?String(c.channel_name).trim():null,channel_code:c.channel_code?String(c.channel_code).trim():null,is_primary:normalizeBoolean(c.is_primary,0),is_active:normalizeBoolean(c.is_active,1)};primaryCount+=row.is_primary;return row;});if(primaryCount>1)throw makeError('Only one primary channel is allowed per brand',422,'VALIDATION_ERROR');if(out.length&&primaryCount===0)out[0].is_primary=1;return out;}
async function validateChannels(channels){const grouped=new Map();channels.forEach(c=>{if(!grouped.has(c.business_unit_id))grouped.set(c.business_unit_id,[]);grouped.get(c.business_unit_id).push(c);});for(const [buId,rows] of grouped){const departments=await DirectoryService.getBusinessUnitDepartments(buId);const valid=new Set(departments.filter(d=>Number(d.is_active)===1).map(d=>Number(d.department_id)));if(rows.some(r=>!valid.has(r.department_id)))throw makeError(`One or more departments are invalid for business unit ${buId}`,422,'INVALID_CHANNEL_DEPARTMENT');}}
async function enrich(brands){if(!brands.length)return brands;const buIds=[],deptIds=[];brands.forEach(b=>(b.channels||[]).forEach(c=>{buIds.push(c.business_unit_id);deptIds.push(c.department_id);}));const [allBu,allDept]=await Promise.all([DirectoryService.getBusinessUnits(),DirectoryService.getDepartments()]);const buMap=new Map(DirectoryService.findBusinessUnitsByIds(allBu,buIds).map(x=>[String(x.id),x]));const deptMap=new Map(DirectoryService.findDepartmentsByIds(allDept,deptIds).map(x=>[Number(x.id),x]));brands.forEach(b=>{b.channels=(b.channels||[]).map(c=>({...c,business_unit:buMap.get(String(c.business_unit_id))||null,department:deptMap.get(Number(c.department_id))||null}));});return brands;}
async function index(query){const rows=await BrandModel.findAll({search:query.search,is_active:query.is_active});await enrich(rows);return rows;}
async function show(id){const row=await BrandModel.findById(id);if(!row)throw makeError('Brand not found',404,'BRAND_NOT_FOUND');await enrich([row]);return row;}
async function store(payload,userId=null,req=null){const normalized=normalizePayload(payload);validatePayload(normalized);normalized.channels=normalizeChannels(normalized.channels);await validateChannels(normalized.channels);return BrandModel.transaction(async connection=>{const id=await BrandModel.create(normalized,connection);await BrandModel.replaceChannels(id,normalized.channels,connection);const created=await BrandModel.findById(id,connection);await enrich([created]);await ActivityLogService.log({user_id:userId,action:'CREATE',entity_type:'master_brands',entity_id:id,description:`Created brand ${created.name}`,before_data:null,after_data:created,metadata:{channel_count:created.channels.length},req,connection});return {message:'Brand created successfully',data:created};});}
async function update(id,payload,userId=null,req=null){const existing=await show(id);const normalized=normalizePayload({...payload,channels:payload.channels??existing.channels});validatePayload(normalized);normalized.channels=normalizeChannels(normalized.channels);await validateChannels(normalized.channels);return BrandModel.transaction(async connection=>{await BrandModel.update(id,normalized,connection);await BrandModel.replaceChannels(id,normalized.channels,connection);const updated=await BrandModel.findById(id,connection);await enrich([updated]);await ActivityLogService.log({user_id:userId,action:'UPDATE',entity_type:'master_brands',entity_id:id,description:`Updated brand ${updated.name}`,before_data:existing,after_data:updated,metadata:{channel_count:updated.channels.length},req,connection});return {message:'Brand updated successfully',data:updated};});}
async function destroy(id,userId=null,req=null){const existing=await show(id);if(await BrandModel.countUsedByItemParents(id))throw makeError('Brand is already used by item parents',409,'MASTER_DATA_IN_USE');await BrandModel.remove(id);await ActivityLogService.log({user_id:userId,action:'DELETE',entity_type:'master_brands',entity_id:id,description:`Deleted brand ${existing.name}`,before_data:existing,after_data:null,req});return {message:'Brand deleted successfully'};}
async function updateStatus(id,is_active,userId=null,req=null){const existing=await show(id);if(!isValidBoolean(is_active))throw makeError('is_active must be 0 or 1',422,'VALIDATION_ERROR');await BrandModel.updateStatus(id,Number(is_active));const updated=await show(id);await ActivityLogService.log({user_id:userId,action:'STATUS_CHANGE',entity_type:'master_brands',entity_id:id,description:`Changed brand ${updated.name} active status`,before_data:existing,after_data:updated,req});return {message:'Brand status updated successfully',data:updated};}
module.exports={index,show,store,update,updateStatus,destroy};
