const CategoryModel=require('../../models/master/category.model');const ActivityLogService=require('../activity-log.service');const DirectoryService=require('../pilargroup-directory.service');
function err(m,s=400,c='ERROR',errors=null){const e=new Error(m);e.statusCode=s;e.code=c;e.errors=errors;return e;}function bool(v){return[0,1,'0','1',true,false].includes(v);}function nb(v,d=0){return v===undefined||v===null||v===''?d:(Number(v)?1:0);}
function normalize(payload){return{detail_category:String(payload.detail_category||'').trim(),sub_category:String(payload.sub_category||'').trim(),main_category:String(payload.main_category||'').trim(),brand_category:String(payload.brand_category||'').trim(),is_active:payload.is_active??1,users:payload.users??[]};}
function validate(p){const e={};for(const f of['detail_category','sub_category','main_category','brand_category'])if(!p[f])e[f]=`${f} is required`;if(!bool(p.is_active))e.is_active='Is active must be 0 or 1';if(!Array.isArray(p.users))e.users='Users must be an array';if(Object.keys(e).length)throw err('Validation failed',422,'VALIDATION_ERROR',e);}
function normalizeUsers(users=[]){const seen=new Set();let pc=0;const out=users.map((u,i)=>{const id=String(u?.central_user_id||'').trim();if(!id||id.length>36)throw err(`Central user is invalid at index ${i}`,422,'VALIDATION_ERROR');if(seen.has(id))throw err('Duplicate central user in request',422,'VALIDATION_ERROR');seen.add(id);const r={central_user_id:id,is_primary:nb(u.is_primary,0),is_active:nb(u.is_active,1)};pc+=r.is_primary;return r;});if(pc>1)throw err('Only one primary user is allowed',422,'VALIDATION_ERROR');if(out.length&&pc===0)out[0].is_primary=1;return out;}
async function validateUsers(users){const all=await DirectoryService.getUsers();const found=new Set(DirectoryService.findUsersByIds(all,users.map(u=>u.central_user_id)).map(u=>String(u.id)));if(users.some(u=>!found.has(u.central_user_id)))throw err('One or more central users not found',404,'CENTRAL_USER_NOT_FOUND');}
async function enrich(rows){if(!rows.length)return rows;const all=await DirectoryService.getUsers();const ids=rows.flatMap(r=>(r.users||[]).map(u=>u.central_user_id));const map=new Map(DirectoryService.findUsersByIds(all,ids).map(u=>[String(u.id),u]));rows.forEach(r=>r.users=(r.users||[]).map(x=>({...x,user:map.get(String(x.central_user_id))||null})));return rows;}
async function index(q){const rows=await CategoryModel.findAll({search:q.search,central_user_id:q.central_user_id,main_category:q.main_category,sub_category:q.sub_category,brand_category:q.brand_category,is_active:q.is_active});await enrich(rows);return rows;}async function show(id){const r=await CategoryModel.findById(id);if(!r)throw err('Category not found',404,'CATEGORY_NOT_FOUND');await enrich([r]);return r;}
async function store(payload,userId=null,req=null){const p=normalize(payload);validate(p);p.users=normalizeUsers(p.users);await validateUsers(p.users);return CategoryModel.transaction(async c=>{const id=await CategoryModel.create(p,c);await CategoryModel.replaceUsers(id,p.users,c);const r=await CategoryModel.findById(id,c);await enrich([r]);await ActivityLogService.log({user_id:userId,action:'CREATE',entity_type:'master_categories',entity_id:id,description:`Created category ${r.detail_category}`,before_data:null,after_data:r,metadata:{user_count:r.users.length},req,connection:c});return{message:'Category created successfully',data:r};});}
async function update(id,payload,userId=null,req=null){const before=await show(id);const p=normalize({...payload,users:payload.users??before.users});validate(p);p.users=normalizeUsers(p.users);await validateUsers(p.users);return CategoryModel.transaction(async c=>{await CategoryModel.update(id,p,c);await CategoryModel.replaceUsers(id,p.users,c);const r=await CategoryModel.findById(id,c);await enrich([r]);await ActivityLogService.log({user_id:userId,action:'UPDATE',entity_type:'master_categories',entity_id:id,description:`Updated category ${r.detail_category}`,before_data:before,after_data:r,metadata:{user_count:r.users.length},req,connection:c});return{message:'Category updated successfully',data:r};});}
async function destroy(id,userId=null,req=null){const before=await show(id);if(await CategoryModel.countUsedByItemParents(id))throw err('Category is already used by item parents',409,'MASTER_DATA_IN_USE');await CategoryModel.remove(id);await ActivityLogService.log({user_id:userId,action:'DELETE',entity_type:'master_categories',entity_id:id,description:`Deleted category ${before.detail_category}`,before_data:before,after_data:null,req});return{message:'Category deleted successfully'};}
async function updateStatus(id,is_active,userId=null,req=null){const before=await show(id);if(!bool(is_active))throw err('is_active must be 0 or 1',422,'VALIDATION_ERROR');await CategoryModel.updateStatus(id,Number(is_active));const r=await show(id);await ActivityLogService.log({user_id:userId,action:'STATUS_CHANGE',entity_type:'master_categories',entity_id:id,description:`Changed category ${r.detail_category} active status`,before_data:before,after_data:r,req});return{message:'Category status updated successfully',data:r};}
module.exports={index,show,store,update,updateStatus,destroy};
