const PortModel=require('../../models/master/port.model');const ActivityLogService=require('../activity-log.service');
function err(m,s=400,c='ERROR',errors=null){const e=new Error(m);e.statusCode=s;e.code=c;e.errors=errors;return e;}function bool(v){return[0,1,'0','1',true,false].includes(v);}function normalize(p){return{country_code:String(p.country_code||'').trim().toUpperCase(),code:String(p.code||'').trim().toUpperCase(),name:String(p.name||'').trim(),is_active:p.is_active??1};}
function validate(p){const e={};if(!/^[A-Z]{2}$/.test(p.country_code))e.country_code='Country code must contain exactly 2 letters';if(!p.code)e.code='Code is required';if(!p.name)e.name='Name is required';if(p.code.length>50)e.code='Code cannot be longer than 50 characters';if(p.name.length>150)e.name='Name cannot be longer than 150 characters';if(!bool(p.is_active))e.is_active='Is active must be 0 or 1';if(Object.keys(e).length)throw err('Validation failed',422,'VALIDATION_ERROR',e);}
async function index(q){return PortModel.findAll({search:q.search,country_code:q.country_code,is_active:q.is_active});}async function show(id){const r=await PortModel.findById(id);if(!r)throw err('Port not found',404,'PORT_NOT_FOUND');return r;}
async function store(payload,userId=null,req=null){const p=normalize(payload);validate(p);const id=await PortModel.create(p);const r=await PortModel.findById(id);await ActivityLogService.log({user_id:userId,action:'CREATE',entity_type:'master_ports',entity_id:id,description:`Created port ${r.name}`,before_data:null,after_data:r,metadata:{country_code:r.country_code,code:r.code},req});return{message:'Port created successfully',data:r};}
async function update(id,payload,userId=null,req=null){const before=await show(id);const p=normalize(payload);validate(p);await PortModel.update(id,p);const r=await PortModel.findById(id);await ActivityLogService.log({user_id:userId,action:'UPDATE',entity_type:'master_ports',entity_id:id,description:`Updated port ${r.name}`,before_data:before,after_data:r,req});return{message:'Port updated successfully',data:r};}
async function destroy(id,userId=null,req=null){const before=await show(id);if(await PortModel.countUsedByItemParents(id))throw err('Port is already used by item parents',409,'MASTER_DATA_IN_USE');await PortModel.remove(id);await ActivityLogService.log({user_id:userId,action:'DELETE',entity_type:'master_ports',entity_id:id,description:`Deleted port ${before.name}`,before_data:before,after_data:null,req});return{message:'Port deleted successfully'};}
async function updateStatus(id,is_active,userId=null,req=null){const before=await show(id);if(!bool(is_active))throw err('is_active must be 0 or 1',422,'VALIDATION_ERROR');await PortModel.updateStatus(id,Number(is_active));const r=await show(id);await ActivityLogService.log({user_id:userId,action:'STATUS_CHANGE',entity_type:'master_ports',entity_id:id,description:`Changed port ${r.name} active status`,before_data:before,after_data:r,req});return{message:'Port status updated successfully',data:r};}
module.exports={index,show,store,update,updateStatus,destroy};
