const VariantModel=require('../../models/master/variant.model');
const ActivityLogService=require('../activity-log.service');
function err(m,s=400,c='ERROR',errors=null){const e=new Error(m);e.statusCode=s;e.code=c;e.errors=errors;return e;}
function bool(v){return[0,1,'0','1',true,false].includes(v);}
function code(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'');}
function normalizeAttribute(p){return{code:code(p.code||p.name),name:String(p.name||'').trim(),is_active:p.is_active??1};}
function validateAttribute(p){const e={};if(!p.code)e.code='Code or name is required';if(!p.name)e.name='Name is required';if(p.code.length>30)e.code='Code cannot be longer than 30 characters';if(p.name.length>100)e.name='Name cannot be longer than 100 characters';if(!bool(p.is_active))e.is_active='Is active must be 0 or 1';if(Object.keys(e).length)throw err('Validation failed',422,'VALIDATION_ERROR',e);}
function normalizeValue(p){return{attribute_id:String(p.attribute_id||'').trim(),code:code(p.code||p.name),name:String(p.name||'').trim(),sort_order:Number(p.sort_order||1),is_active:p.is_active??1};}
function validateValue(p){const e={};if(!p.attribute_id)e.attribute_id='Attribute is required';if(!p.code)e.code='Code or name is required';if(!p.name)e.name='Name is required';if(p.code.length>50)e.code='Code cannot be longer than 50 characters';if(p.name.length>150)e.name='Name cannot be longer than 150 characters';if(!Number.isInteger(p.sort_order)||p.sort_order<1)e.sort_order='Sort order must be a positive integer';if(!bool(p.is_active))e.is_active='Is active must be 0 or 1';if(Object.keys(e).length)throw err('Validation failed',422,'VALIDATION_ERROR',e);}
async function attributes(q){return VariantModel.findAttributes(q);} async function attribute(id){const r=await VariantModel.findAttributeById(id);if(!r)throw err('Variant attribute not found',404);return r;}
async function createAttribute(payload,userId,req){const p=normalizeAttribute(payload);validateAttribute(p);const id=await VariantModel.createAttribute(p);const r=await attribute(id);await ActivityLogService.log({user_id:userId,action:'CREATE',entity_type:'master_variant_attributes',entity_id:id,description:`Created variant attribute ${r.name}`,after_data:r,req});return r;}
async function updateAttribute(id,payload,userId,req){const before=await attribute(id),p=normalizeAttribute(payload);validateAttribute(p);await VariantModel.updateAttribute(id,p);const r=await attribute(id);await ActivityLogService.log({user_id:userId,action:'UPDATE',entity_type:'master_variant_attributes',entity_id:id,description:`Updated variant attribute ${r.name}`,before_data:before,after_data:r,req});return r;}
async function statusAttribute(id,v,userId,req){const before=await attribute(id);if(!bool(v))throw err('is_active must be 0 or 1',422);await VariantModel.updateAttributeStatus(id,Number(v));const r=await attribute(id);await ActivityLogService.log({user_id:userId,action:'STATUS_CHANGE',entity_type:'master_variant_attributes',entity_id:id,description:`Changed variant attribute ${r.name} status`,before_data:before,after_data:r,req});return r;}
async function deleteAttribute(id,userId,req){const before=await attribute(id);if(await VariantModel.countAttributeUsage(id))throw err('Variant attribute is already in use',409,'MASTER_DATA_IN_USE');await VariantModel.deleteAttribute(id);await ActivityLogService.log({user_id:userId,action:'DELETE',entity_type:'master_variant_attributes',entity_id:id,description:`Deleted variant attribute ${before.name}`,before_data:before,req});}
async function values(q){return VariantModel.findValues(q);} async function value(id){const r=await VariantModel.findValueById(id);if(!r)throw err('Variant value not found',404);return r;}
async function createValue(payload,userId,req){const p=normalizeValue(payload);validateValue(p);const a=await VariantModel.findAttributeById(p.attribute_id);if(!a)throw err('Variant attribute not found',404);const id=await VariantModel.createValue(p);const r=await value(id);await ActivityLogService.log({user_id:userId,action:'CREATE',entity_type:'master_variant_values',entity_id:id,description:`Created variant value ${r.name}`,after_data:r,req});return r;}
async function updateValue(id,payload,userId,req){const before=await value(id),p=normalizeValue(payload);validateValue(p);if(!(await VariantModel.findAttributeById(p.attribute_id)))throw err('Variant attribute not found',404);await VariantModel.updateValue(id,p);const r=await value(id);await ActivityLogService.log({user_id:userId,action:'UPDATE',entity_type:'master_variant_values',entity_id:id,description:`Updated variant value ${r.name}`,before_data:before,after_data:r,req});return r;}
async function statusValue(id,v,userId,req){const before=await value(id);if(!bool(v))throw err('is_active must be 0 or 1',422);await VariantModel.updateValueStatus(id,Number(v));const r=await value(id);await ActivityLogService.log({user_id:userId,action:'STATUS_CHANGE',entity_type:'master_variant_values',entity_id:id,description:`Changed variant value ${r.name} status`,before_data:before,after_data:r,req});return r;}
async function deleteValue(id,userId,req){const before=await value(id);if(await VariantModel.countValueUsage(id))throw err('Variant value is already in use',409,'MASTER_DATA_IN_USE');await VariantModel.deleteValue(id);await ActivityLogService.log({user_id:userId,action:'DELETE',entity_type:'master_variant_values',entity_id:id,description:`Deleted variant value ${before.name}`,before_data:before,req});}
module.exports={attributes,attribute,createAttribute,updateAttribute,statusAttribute,deleteAttribute,values,value,createValue,updateValue,statusValue,deleteValue};
